/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonComponent {
        "label": string;
        "type": string;
    }
    interface CardComponent {
        "cardtitle": string;
    }
    interface CheckboxComponent {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
    }
    interface HeaderComponent {
        "logo": string;
    }
    interface InputComponent {
        "disabled": boolean;
        "label": string;
    }
}
declare global {
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLCardComponentElement extends Components.CardComponent, HTMLStencilElement {
    }
    var HTMLCardComponentElement: {
        prototype: HTMLCardComponentElement;
        new (): HTMLCardComponentElement;
    };
    interface HTMLCheckboxComponentElement extends Components.CheckboxComponent, HTMLStencilElement {
    }
    var HTMLCheckboxComponentElement: {
        prototype: HTMLCheckboxComponentElement;
        new (): HTMLCheckboxComponentElement;
    };
    interface HTMLHeaderComponentElement extends Components.HeaderComponent, HTMLStencilElement {
    }
    var HTMLHeaderComponentElement: {
        prototype: HTMLHeaderComponentElement;
        new (): HTMLHeaderComponentElement;
    };
    interface HTMLInputComponentElement extends Components.InputComponent, HTMLStencilElement {
    }
    var HTMLInputComponentElement: {
        prototype: HTMLInputComponentElement;
        new (): HTMLInputComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-component": HTMLButtonComponentElement;
        "card-component": HTMLCardComponentElement;
        "checkbox-component": HTMLCheckboxComponentElement;
        "header-component": HTMLHeaderComponentElement;
        "input-component": HTMLInputComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonComponent {
        "label"?: string;
        "type"?: string;
    }
    interface CardComponent {
        "cardtitle"?: string;
    }
    interface CheckboxComponent {
        "checked"?: boolean;
        "disabled"?: boolean;
        "label"?: string;
    }
    interface HeaderComponent {
        "logo"?: string;
    }
    interface InputComponent {
        "disabled"?: boolean;
        "label"?: string;
    }
    interface IntrinsicElements {
        "button-component": ButtonComponent;
        "card-component": CardComponent;
        "checkbox-component": CheckboxComponent;
        "header-component": HeaderComponent;
        "input-component": InputComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "card-component": LocalJSX.CardComponent & JSXBase.HTMLAttributes<HTMLCardComponentElement>;
            "checkbox-component": LocalJSX.CheckboxComponent & JSXBase.HTMLAttributes<HTMLCheckboxComponentElement>;
            "header-component": LocalJSX.HeaderComponent & JSXBase.HTMLAttributes<HTMLHeaderComponentElement>;
            "input-component": LocalJSX.InputComponent & JSXBase.HTMLAttributes<HTMLInputComponentElement>;
        }
    }
}
